function onCreate()
    makeLuaSprite('airshipSky','airship/newAirship/fartingSky',-800,-200)
    addLuaSprite('airshipSky',false)
    makeLuaSprite('airshipBCloud','airship/newAirship/backSkyyellow',-1190,220)
    setProperty('airshipBCloud.alpha',0.8)
    makeLuaSprite('airShipWindow','airship/newAirship/window',-1100,-900)
    addLuaSprite('airShipWindow',false)
    setScrollFactor('airshipBCloud',0.7,0.7)
    addLuaSprite('airshipBCloud',false)
    makeLuaSprite('airshipCloud','airship/newAirship/cloudYellow1',-1600,200)
    setScrollFactor('airshipCloud',0.85,0.85)
    if not lowQuality then
        makeLuaSprite('airshipCloud2','airship/newAirship/cloudYellow2',-900,200)
        setScrollFactor('airshipCloud2',0.7,0.7)
        addLuaSprite('airshipCloud2',false)
        makeLuaSprite('airshipCloud3','airship/newAirship/cloudYellow3',1300,220)
        setScrollFactor('airshipCloud3',0.7,0.7)
        addLuaSprite('airshipCloud3',false)
    end
    addLuaSprite('airshipCloud',false)
    makeLuaSprite('airshipBGround','airship/newAirship/backDlowFloor',-710,270)
    addLuaSprite('airshipBGround',false)
    makeLuaSprite('airshipGround','airship/newAirship/DlowFloor',-2480,330)
    addLuaSprite('airshipGround',false)
end